version: '3'

services:
  webrtc:
    build:
        context: '.'
        dockerfile: Dockerfile
    container_name: webrtc
    restart: always
    ports:
      - 8042:8042
    expose:
      - 8042
    environment:
      VIRTUAL_HOST: webrtc.thyiad.top

networks:
  default:
    external:
      name: nginx-proxy
