version: '3'

services:
  my_puppeteer:
    build:
        context: './image-app'
        dockerfile: Dockerfile
    container_name: my_puppeteer
    restart: always
    ports:
      - 8043:8080
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: puppeteer.thyiad.top

networks:
  default:
    external:
      name: nginx-proxy
